export const team_info = [
	{
		name: 'Todd McKenzie',
		role: 'Team Lead + Django Backend Developer',
		img_path: 'todd_pixel.png',
		link_title: 'GitHub',
		webpage_url: 'https://toddmckenzie.dev/',
		linkedin_url: 'https://www.linkedin.com/in/todd-mckenzie/',
		github_url: 'https://github.com/toddmckenzie',
		twitter_url: '',
		bio: 'Web 19 Labs 17 TL CS25 TL',
	},
	{
		name: 'Jordan Doan',
		role: 'Django Backend Developer',
		img_path: 'jordan_pixel.png',
		link_title: 'website',
		webpage_url: 'http://jordan-doan.com/',
		linkedin_url: 'https://www.linkedin.com/in/jordan-doan-790694156/',
		github_url: 'https://github.com/jordandoan',
		twitter_url: '',
		bio: 'i like chimkin nunget',
	},
	{
		name: 'Jonathan Ho',
		role: 'React Frontend Developer',
		img_path: 'jonathan_pixel.png',
		link_title: 'LinkedIn',
		webpage_url: 'https://jonathan-ho.dev',
		linkedin_url: 'https://www.linkedin.com/in/jonathan-y-ho/',
		github_url: 'https://github.com/Jonathan-YungHsin-Ho',
		twitter_url: 'https://twitter.com/JonathanHoDev',
		bio: '**Web22*Labs18*CS25**',
	},
	{
		name: 'Nick Gonzalez',
		role: 'React Frontend Developer',
		img_path: 'nick_pixel.png',
		link_title: 'GitHub',
		webpage_url: '',
		linkedin_url: 'https://www.linkedin.com/in/nick-gonzalez-0541bb111/',
		github_url: 'https://github.com/NickGonzalez04',
		twitter_url: '',
		bio: 'Web22 | Labs18 QualityHub+InterviewQ | Create Your Own Adventure',
	},
	{
		name: 'Brandon Pampuch',
		role: 'Moral Support',
		img_path: 'brandon_pixel.png',
		link_title: 'GitHub',
		webpage_url: '',
		linkedin_url: '',
		github_url: 'https://github.com/Brandon-Pampuch',
		twitter_url: '',
		bio: 'WD 19',
	},
];
